### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by haberdashPI**
A few fixes:

- I believe yarn is required (fixed my problem at least)
- It would be good to at least indicate *an* installation method for `devspace`.
- Likewise, it's probably good to at least say that NPM is required, and an example of how to install it

### CODE REVIEW

**Comment by omus** [comment]
>     * It would be good to at least indicate _an_ installation method for `devspace`.

Agreed. As `yarn` and `npm` is only required for `devspace` that should all be rolled into the same bullet

**Review by kolia — COMMENTED** [review]
You can also install devspace using the `Linux` instructions (that's how I installed it), so `npm` / `yarn` don't have to be a dependency.

**Comment by omus** [comment]
We should also include a link to the devspace installation guide: https://devspace.sh/cli/docs/getting-started/installation

**Comment by haberdashPI** [comment]
```
npm i -g devspace
``` 

I got errors about yarn missing. Haven't investigated why, but this seems to diverge from the directions on the devspace website.

**Review by kolia — APPROVED** [review]
:+1:

**Pull request merged**
